BladeMill.Web/Controllers/BMUserController.cs
using BladeMill.BLL.DAL;
using BladeMill.BLL.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace BladeMill.Web.Controllers
{
    public class BMUserController : Controller
    {
        private readonly IBMUserService _bmUserService;

        public BMUserController(IBMUserService bmUserService)
        {
            _bmUserService = bmUserService;
        }
        // GET: BMUserController
        public async Task<IActionResult> Index()
        {
            var users = await _bmUserService.GetAll();
            return View(users);
        }

        // GET: BMUserController/Details/5
        public async Task<ActionResult<BMUserDto>> Details(int id)
        {
            var user = await _bmUserService.GetById(id);
            return View(user);
        }

        // GET: BMUserController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: BMUserController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: BMUserController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: BMUserController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: BMUserController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: BMUserController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

BladeMill.Web/Controllers/ToolNcController.cs
using BladeMill.BLL.Models;
using BladeMill.BLL.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace BladeMill.Web.Controllers
{
    public class ToolNcController : Controller
    {
        // GET: ToolNcController
        private ToolNcService _toolNcService;
        private NcMainProgramService _ncMainProgramService;

        public ToolNcController()
        {
            _toolNcService = new ToolNcService();
            _ncMainProgramService = new NcMainProgramService();
        }
        public ActionResult Index()
        {
            var model = _toolNcService.GetAllToolsFromCurrentXml();
            return View(model);
        }

        // GET: ToolNcController/Details/5
        public ActionResult Details(int id)
        {
            var model = _toolNcService.GetById(id);
            return View(model);
        }

        // GET: ToolNcController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ToolNcController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ToolNcController/Edit/5
        public ActionResult Edit(int id)
        {
            var model = _toolNcService.GetById(id);
            return View(model);
        }

        // POST: ToolNcController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Tool model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(model);
                }

                //var id = TempData["id"] as string;
                //var user = _userService.GetById(id);
                //_transactionService.AddTransactionByUser(model, user);

                //_toolNcService.Update(model);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ToolNcController/Delete/5
        public ActionResult Delete(int id)
        {
            var model = _toolNcService.GetById(id);
            return View(model);
        }

        // POST: ToolNcController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Tool model)
        {
            try
            {
                _toolNcService.Delete(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

BladeMill.Web/Controllers/UserController.cs
using AutoMapper;
using BladeMill.BLL.DAL;
using BladeMill.BLL.Interfaces;
using BladeMill.BLL.Models;
using BladeMill.BLL.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BladeMill.Web.Controllers
{
    public class UserController : Controller
    {
        private readonly ILogger<UserController> _logger;
        private readonly IUserService _userService;
        private string _sso = "";
        private readonly IMapper _mapper;

        public UserController(IUserService userService, ILogger<UserController> logger, IMapper mapper)
        {
            _userService = userService;
            _logger = logger;
            _mapper = mapper;
        }

        private User MapUserDtoToUzytkownik(UserDto userDto)
        {
            return new User
            {
                Id = userDto.Id,
                Created = userDto.Created,
                FirstName = userDto.FirstName,
                LastName = userDto.LastName,
                Sso = userDto.Sso             
            };
        }

        public async Task<ActionResult> Index()
        {
            var model = new List<User>() { };
            _logger.LogInformation("Sciagam dane z bazy danych...");
            var dataFromBase = await _userService.FindAll();
            model = _mapper.Map<List<User>>(dataFromBase);

            //model = dataFromBase.Select(MapUserDtoToUzytkownik);//reczne mapowanie na model

            if (!dataFromBase.Any())
                return BadRequest($"Brak uzytkowników!");

            return View(model);//tutaj tylko user model wchodzi!!
        }

        // GET: UserControlle/Details/5
        public async Task<ActionResult> Details(int id)
        {
            var dataFromBase = await _userService.FindById(id);
            var model = _mapper.Map<User>(dataFromBase);

            if (model == null)
                return BadRequest($"Brak uzytkownika!");

            _logger.LogInformation($"Uzytkownik {model.LastName} uruchomil szczegoly o godz {DateTime.Now}");
            return View(model);
        }

        public ActionResult EmptyList(string user)//TODO to musi byc!!
        {
            ViewBag.User = user;
            return View();
        }

        // GET: UserControlle/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UserControlle/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(UserDto model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(model);
                }

                await _userService.Create(model);

                //walidacja SSO
                //var maxSsoLenght = 9;
                //var validate = new UserValidator();
                //var message = validate.ValidateSSO(model.Sso, maxSsoLenght, _db);
                //if (!string.IsNullOrEmpty(message))
                //    return Content($"{message}");
                //var userDto = new UserDataBaseSet(_db);
                //userDto.AddUserDto(model);
                //patrz EntityFrameworkCore.03_ModelMapping / Configuration jak nadac properties/walidacje inna niz tutaj?
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: UserControlle/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            var dataFromBase = await _userService.FindById(id);
            var model = _mapper.Map<User>(dataFromBase);
            if (model == null)
                return BadRequest($"Brak uzytkownika!");
            _logger.LogInformation($"Uzytkownik {model.LastName} uruchomil edycje o godz {DateTime.Now}");
            return View(model);
        }

        // POST: UserControlle/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, UserDto model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(model);
                }

                await _userService.Update(model);

                //var maxSsoLenght = 9;
                //var validate = new UserValidator();
                //var message = validate.ValidateSSO(model.Sso, maxSsoLenght, _db);
                //if (!string.IsNullOrEmpty(message))
                //    return Content($"{message}");
                //var userDto = new UserDataBaseSet(_db);
                //userDto.UpdateUserDto(model, id);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        //GET: UserControlle/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            var dataFromBase = await _userService.FindById(id);
            var model = _mapper.Map<User>(dataFromBase);
            if (model == null)
                return BadRequest($"Brak uzytkownika!");
            return View(model);
        }

        // POST: UserControlle/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id, UserDto model)
        {
            try
            {
                await _userService.Delete(model);
                _logger.LogInformation($"Uzytkownik {model.LastName} zostal usuniety o godz {DateTime.Now}");
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

BladeMill.Web/Controllers/UserDtoController.cs
using AutoMapper;
using BladeMill.BLL.DAL;
using BladeMill.BLL.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BladeMill.Web.Controllers
{
    public class UserDtoController : Controller
    {
        // GET: UserDtoController

        private UserServiceWithoutDatabase _userService;
        private readonly IMapper _mapper;
        private readonly ILogger<HomeController> _logger;

        public UserDtoController(UserServiceWithoutDatabase userService, IMapper mapper, ILogger<HomeController> logger)
        {
            _userService = userService;
            _mapper = mapper;
            _logger = logger;
        }

        public ActionResult Index()
        {
            var dto = _userService.GetAll();//wziete z modelu
            _logger.LogInformation("Sciagam dane z modelu z Service ...");
            //var model = dto.Select(e => _mapper.Map<UserDto>(e)); //to tez dziala
            var model = _mapper.Map<List<UserDto>>(dto);// mapowanie na dto co checemy pokazac tylko!
            _logger.LogInformation("Mapowanie automatyczne z User na UserDto");
            return View(model);
        }

        // GET: UserDtoController/Details/5
        public ActionResult Details(int id)
        {
            var dto = _userService.GetById(id);//wziete z modelu
            var model = _mapper.Map<UserDto>(dto);

            if (model == null)
                return BadRequest($"Brak uzytkownika!");

            return View(model);
        }

        // GET: UserDtoController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UserDtoController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: UserDtoController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: UserDtoController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: UserDtoController/Delete/5
        public ActionResult Delete(int id)
        {
            var model = _userService.GetById(id);
            ViewBag.User = model.LastName;
            _logger.LogWarning("Get({Id}) you cannot delete user with Id", id);
            return RedirectToAction("EmptyList", new { User = model.LastName });
            return View();
        }

        // POST: UserDtoController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
        public ActionResult EmptyList(string user)//TODO to musi byc!!
        {
            ViewBag.User = user;
            return View();
        }
    }
}

BladeMill.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BladeMill.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body style="background-color:#D7DBDD">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"> <img src="BladeMillLogo.ico" class="d-inline-block align-middle rounded" width="100" alt="Logo">BladeMill</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

@*                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-center">
                    <partial name="_PartialUser" />
                    <partial name="_PartialMainProgram" />
                    <partial name="_PartialXml" />
                    <partial name="_PartialHelpProgram" />
                </div>*@

                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <partial name="_PartialUser" />   
                        <ul></ul>
                        <partial name="_PartialMainProgram" />
                        <ul></ul>
                        <partial name="_PartialXml" />
                        <ul></ul>
                        <partial name="_PartialHelpProgram" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - BladeMill.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BladeMill.Web/Views/Shared/_PartialHelpProgram.cshtml
                        <div class="dropdown">
                            <a class="btn btn-success dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Help Programs
                            </a>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                <a class="dropdown-item" asp-area="" asp-controller="ProgramExe" asp-action="Index">Help programs</a> <br />                     
                            </div>
                        </div>

BladeMill.Web/Views/Shared/_PartialMainProgram.cshtml
                        <div class="dropdown">
                            <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Profile Program
                            </a>

                            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                <a class="dropdown-item" asp-area="" asp-controller="NcMainProgram" asp-action="Index">Main Programs</a> <br />
                                <a class="dropdown-item" asp-area="" asp-controller="ToolNc" asp-action="Index">BM tools Print</a> <br />                          
                            </div>
                        </div>

BladeMill.Web/Views/Shared/_PartialUser.cshtml
                        <div class="dropdown">
                            <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Profile Users
                            </a>

                            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                <a class="dropdown-item" asp-area="" asp-controller="User" asp-action="Index">BM users (z bazy)</a> <br />
                                <a class="dropdown-item" asp-area="" asp-controller="UserFromService" asp-action="Index">BM users (z serwisu)</a> <br />
                                <a class="dropdown-item" asp-area="" asp-controller="UserDto" asp-action="Index">BM users Mapper (z serwisu)</a> <br />
                                <a class="dropdown-item" asp-area="" asp-controller="BMUser" asp-action="Index">BM users from database</a> <br />                          
                            </div>
                        </div>

BladeMill.Web/Views/Shared/_PartialXml.cshtml
<div class="dropdown">
    <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Profile Xml
    </a>

    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
        <a class="dropdown-item" asp-area="" asp-controller="InputDataXml" asp-action="Index">View inputdata.xml</a> <br />
        <a class="dropdown-item" asp-area="" asp-controller="Varpool" asp-action="Index">View varpool.xml</a> <br />
        <a class="dropdown-item" asp-area="" asp-controller="ApplicationXmlConf" asp-action="Index">View Application.xml.conf</a> <br />
    </div>
</div>